### ISSUE TITLE
BDSP High CPU

### ISSUE THREAD

**Issue by Poke-Legend** [kwsch/SysBot.NET#204] opened 2024-10-06 05:56 UTC
When running Brilliant Diamond & Shinning Pearl for a day, the CPU goes nuts. I am unsure what is causing it. Other games such as Scarlet & Violet, Let's Go Pikachu & Eevee, Legends of Arceus and Sword & Shield are running just fine. It's just BDSP causing High CPU loads after a full day. I have tested this on few computers and laptops with same results.

**Comment by kwsch** [comment] 2024-10-06 06:11
Probably AutoLegalityMod getting stuck in a loop for a bad request, and not timing out the request properly.

**Comment by Lusamine** [comment] 2024-10-07 04:19
I will note a couple of things here:
1. You are not running our SysBot, because we do not have support for LGPE. Does this same issue occur on unmodified SysBot.NET? Please only report issues that occur on unmodified SysBot.NET; issues that occur on forks should go to the fork owner.
2. If it does occur on unmodified SysBot.NET, look at the text logs for the last sets requested before the high CPU became a problem. Try requesting those sets yourself to see if it causes the problem. DO NOT POST THE SETS HERE BECAUSE IT LETS PEOPLE BREAK EVERYONE'S BOTS.  However, let me know if you are able to replicate the problem this way.

**Comment by Lusamine** [comment] 2024-10-07 13:29
Your language is confusing. This is the original repository, not a fork. Gengar's modified code would be a fork. 

I have a good idea what is happening, but I do not need a screenshot of a Discord conversation. Please follow these instructions: 
1. Test only on the unmodified program. Do not test on a fork and report problems here. 
2. Go through the text logs and try requesting sets until you find one that causes the problem. 
3. Tell me here if you find a set that causes the problem. DO NOT POST THE SET HERE, just say whether you found a set or not.

I cannot provide help unless you test on the unmodified program and find the details for how to replicate.

**Comment by Lusamine** [comment] 2024-10-19 06:01
Closing this as no information has been provided to replicate the problem on the unmodified program.

If you have more information, please provide what I requested above as well as a screenshot of the problem. This will help us to understand exactly what the issue is (high CPU? high memory allocation? something else?).

**Closed by Lusamine** 2024-10-19 06:01 UTC
